name: Build Uncrustify

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: UEFI

jobs:
  build-macos:
    name: macOS
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python3 -m venv ~/pyenv
          source ~/pyenv/bin/activate
          python3 -m pip install -r requirements.txt

      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - name: Build Uncrustify
        run: |
          source ~/pyenv/bin/activate
          cd uncstrap && python3 ./uncstrap.py -b
          echo "UNC_SHA=$(cat unc-sha.txt)" >> $GITHUB_ENV

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Uncrustify-Darwin-${{ env.UNC_SHA }}
          path: ./uncstrap/uncrustify
          if-no-files-found: error

  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake curl git
          sudo python3 -m pip install -r requirements.txt

      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - name: Build Uncrustify
        run: |
          cd uncstrap && python3 ./uncstrap.py -b
          echo "UNC_SHA=$(cat unc-sha.txt)" >> $GITHUB_ENV

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Uncrustify-Linux-${{ env.UNC_SHA }}
          path: ./uncstrap/uncrustify
          if-no-files-found: error

  build-windows:
    name: Windows VS2019
    runs-on: windows-2019
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          choco install cmake make --no-progress
          python3 -m pip install -r requirements.txt

      - name: CI Bootstrap
        run: |
          src=$(curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - name: Build Uncrustify
        run: |
          cd uncstrap && python3 ./uncstrap.py -b
          echo "UNC_SHA=$(cat unc-sha.txt)" >> $GITHUB_ENV

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Uncrustify-Windows-${{ env.UNC_SHA }}
          path: ./uncstrap/uncrustify.exe
          if-no-files-found: error
